# Config file for automatic testing at travis-ci.org

dist: xenial

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  fast_finish: true

install:
  - pip install -r requirements_test.txt
  - pip install tox-travis

before_script: flake8

script: tox

after_success: codecov
