# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"

matrix:
  fast_finish: true

install:
  - pip install -r requirements_test.txt
  - pip install tox-travis

before_script: flake8

script: tox

after_success: codecov
